CREATE DATABASE IF NOT EXISTS db01;

use db01;

DROP TABLE IF EXISTS EMP3;
DROP TABLE IF EXISTS DEPT3;

CREATE TABLE DEPT3 (
	DEPTNO	INT AUTO_INCREMENT NOT NULL,
	DNAME	  VARCHAR(14),
	LOC		  VARCHAR(13),
	CONSTRAINT DEPT3_PRIMARY_KEY PRIMARY KEY (DEPTNO)
);

INSERT INTO DEPT3 (DNAME,LOC) VALUES ('財務部','臺灣台北');
INSERT INTO DEPT3 (DNAME,LOC) VALUES ('研發部','臺灣新竹');
INSERT INTO DEPT3 (DNAME,LOC) VALUES ('業務部','美國紐約');
INSERT INTO DEPT3 (DNAME,LOC) VALUES ('生管部','中國上海');


CREATE TABLE EMP3 (
	EMPNO     INT AUTO_INCREMENT NOT NULL,
	ENAME     VARCHAR(10),
	JOB       VARCHAR(9),
	HIREDATE  DATE,
	SAL       DECIMAL(7,2),
	COMM      DECIMAL(7,2),
	upFiles   LONGBLOB,
	DEPTNO    INT NOT NULL,    
	CONSTRAINT EMP3_DEPTNO_FK FOREIGN KEY (DEPTNO) REFERENCES DEPT3 (DEPTNO),
	CONSTRAINT EMP3_EMPNO_PK PRIMARY KEY (EMPNO)
) AUTO_INCREMENT = 7001;

INSERT INTO EMP3 (ENAME, JOB, HIREDATE, SAL, COMM, upFiles, DEPTNO)  VALUES ('KING'  ,'PRESIDENT',STR_TO_DATE('1981-11-17','%Y-%m-%d'),5000.5,0.0 ,null,1);
INSERT INTO EMP3 (ENAME, JOB, HIREDATE, SAL, COMM, upFiles, DEPTNO)  VALUES ('BLAKE' ,'MANAGER'  ,STR_TO_DATE('1981-05-01','%Y-%m-%d'),2850.0,0.0 ,null,3);
INSERT INTO EMP3 (ENAME, JOB, HIREDATE, SAL, COMM, upFiles, DEPTNO)  VALUES ('CLARK' ,'MANAGER'  ,STR_TO_DATE('1981-01-09','%Y-%m-%d'),2450.0,0.0 ,null,1);
INSERT INTO EMP3 (ENAME, JOB, HIREDATE, SAL, COMM, upFiles, DEPTNO)  VALUES ('JONES' ,'MANAGER'  ,STR_TO_DATE('1981-04-02','%Y-%m-%d'),2975.0,0.0 ,null,2);
INSERT INTO EMP3 (ENAME, JOB, HIREDATE, SAL, COMM, upFiles, DEPTNO)  VALUES ('MARTIN','SALESMAN' ,STR_TO_DATE('1981-09-28','%Y-%m-%d'),1250.0,1400,null,3);
INSERT INTO EMP3 (ENAME, JOB, HIREDATE, SAL, COMM, upFiles, DEPTNO)  VALUES ('ALLEN' ,'SALESMAN' ,STR_TO_DATE('1981-02-02','%Y-%m-%d'),1600.0,300 ,null,3);
INSERT INTO EMP3 (ENAME, JOB, HIREDATE, SAL, COMM, upFiles, DEPTNO)  VALUES ('TURNER','SALESMAN' ,STR_TO_DATE('1981-09-28','%Y-%m-%d'),1500.0,0.0 ,null,3);
INSERT INTO EMP3 (ENAME, JOB, HIREDATE, SAL, COMM, upFiles, DEPTNO)  VALUES ('JAMES' ,'CLERK'    ,STR_TO_DATE('1981-12-03','%Y-%m-%d'), 950.0,0.0 ,null,3);
INSERT INTO EMP3 (ENAME, JOB, HIREDATE, SAL, COMM, upFiles, DEPTNO)  VALUES ('WARD'  ,'SALESMAN' ,STR_TO_DATE('1981-02-22','%Y-%m-%d'),1250.0,500 ,null,3);
INSERT INTO EMP3 (ENAME, JOB, HIREDATE, SAL, COMM, upFiles, DEPTNO)  VALUES ('FORD'  ,'ANALYST'  ,STR_TO_DATE('1981-12-03','%Y-%m-%d'),3000.0,0.0 ,null,2);
INSERT INTO EMP3 (ENAME, JOB, HIREDATE, SAL, COMM, upFiles, DEPTNO)  VALUES ('SMITH' ,'CLERK'    ,STR_TO_DATE('1980-12-17','%Y-%m-%d'), 800.0,0.0 ,null,2);
INSERT INTO EMP3 (ENAME, JOB, HIREDATE, SAL, COMM, upFiles, DEPTNO)  VALUES ('SCOTT' ,'ANALYST'  ,STR_TO_DATE('1981-12-09','%Y-%m-%d'),3000.0,0.0 ,null,2);
INSERT INTO EMP3 (ENAME, JOB, HIREDATE, SAL, COMM, upFiles, DEPTNO)  VALUES ('ADAMS' ,'CLERK'    ,STR_TO_DATE('1983-01-12','%Y-%m-%d'),1100.0,0.0 ,null,2);
INSERT INTO EMP3 (ENAME, JOB, HIREDATE, SAL, COMM, upFiles, DEPTNO)  VALUES ('MILLER','CLERK'    ,STR_TO_DATE('1982-01-23','%Y-%m-%d'),1300.0,0.0 ,null,1);
